services:
  # mongodb:
  #   image: "mongo:latest"
  #   environment:
  #     MONGO_INITDB_DATABASE: "mydatabase"
  #     MONGO_INITDB_ROOT_USERNAME: "root"
  #     MONGO_INITDB_ROOT_PASSWORD: "secret"
  #   ports:
  #     - "27017"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "max_amps"
      POSTGRES_USER: "${PSQL_USERNAME}"
      POSTGRES_PASSWORD: "${PSQL_PASSWORD}"
    ports:
      - "5432"
  redis:
    image: "redis:latest"
    ports:
      - "6379"
